### ISSUE TITLE
Fail to detect anime with version after the episode

### ISSUE THREAD

**Issue by MeGaNeKoS** [igorcmoura/anitopy#10]
The library failed to recognize some anime if the versioning right next to the episode number:
`[Judas] Aharen-san wa Hakarenai - S01E06v2.mkv`

**Comment by igorcmoura** [comment]
Thank you for the report!
I fixed and released it with the version 2.1.1

**Comment by MeGaNeKoS** [comment]
Unfortunately, this also happend on the `[Judas] One Piece - 1009v2.mkv` but working fine on `[GST] Isekai Ojisan - 02v2 [1080p][Multi-Subs].mkv `.

```python
anitopy.parse("[Judas] One Piece - 1009v2.mkv")
{'file_name': '[Judas] One Piece - 1009v2.mkv', 'file_extension': 'mkv', 'anime_title': 'One Piece - 1009v2', 'release_group': 'Judas'}

anitopy.parse("[GST] Isekai Ojisan - 02v2 [1080p][Multi-Subs].mkv ")
{'file_name': '[GST] Isekai Ojisan - 02v2 [1080p][Multi-Subs].mkv ', 'video_resolution': '1080p', 'subtitles': 'Multi-Subs', 'episode_number': '02', 'release_version': '2', 'anime_title': 'Isekai Ojisan', 'release_group': 'GST', 'episode_title': 'mkv'}
```

**Comment by MeGaNeKoS** [comment]
After checking the code, This happend from the parse_number.py on function match_single_episode_pattern. In here, the pattern limit the max episode to 1000. By increasing the limit it can detect correctly now. I think it safe to set the max episode to 4 digit now since some anime like one piece, detective conan already reach 1000 eps.

```
- pattern = '(\d{1,3})[vV](\d)$'
+ pattern = '(\d{1,4})[vV](\d)$'
```

**Comment by igorcmoura** [comment]
I wonder if it would be safe to consider any amount of numbers for the episode pattern. I tried changing it to `(\d+)` for all episode patterns and running the test table, and everything went fine. So I'm not sure why erengy chose to limit it to 3 numbers only.

Anyway, we can change it to 4 for now since it's known that no anime has more than 9999 episodes so far.

**Comment by igorcmoura** [comment]
I've released the version 2.1.2rc1 and will let you test it before releasing the final version.

Could you do a `pip install anitopy==2.1.2rc1` and test if everything is fine?

**Comment by MeGaNeKoS** [comment]
Everything work fine to me. I think max it on 4 is good enough for now. We still have more than 80+ year to reach eps 9k.

Also, dont forget to increase the `EPISODE_NUMBER_MAX` in `parser_number.py` as well.

**Comment by igorcmoura** [comment]
Oh, I forgot about this constant...

Looking at it's use case, it's to avoid years in filenames like `Kimi no Na wa 2016 720p BluRay x264 AAC-Shiniori.mp4` from being parsed as the episode number (but it doesn't parse it as the year either so... that's another problem).

I've looked at the [animes with most episodes](https://en.wikipedia.org/wiki/List_of_anime_series_by_episode_count) and currently there are only 3 with more than 1900 episodes: [Sazae-san](https://en.wikipedia.org/wiki/Sazae-san), [Nintama Rantarō](https://en.wikipedia.org/wiki/Nintama_Rantar%C5%8D) and [Ojarumaru](https://en.wikipedia.org/wiki/Ojarumaru). So, increasing the value of this constant would result in filenames containing the year being parsed incorrectly for the sake of this 3 edge cases.

Therefore, I'd prefer to keep this constant at it's current value. What do you think?

**Comment by MeGaNeKoS** [comment]
Hmm. since only a few anime that can reach that much episode, I think it's better to keep this value as it and add option for the developer to increase the value on the runtime. 
Also, i dont think we need to push this changes yet. It's better we add this after change this module from singletons to instance based. Since it really mess up when using multi thread.

```py
import anitopy

anitopy.parse("[ASW] Detective Conan - 2012 [1080p HEVC x265 10Bit][AAC]", max_episode=3000)
{
 'file_name': '[ASW] Detective Conan - 2012 [1080p HEVC x265 10Bit][AAC]',
 'video_resolution': '1080p',
 'video_term': ['HEVC', 'x265', '10Bit'],
 'audio_term': 'AAC',
 'episode_number': '2012',
 'anime_title': 'Detective Conan',
 'release_group': 'ASW'
}
```
